#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 26 15:34:15 2023

@author: mehdu
"""

arr = np.array([-5, 4, -2, 3, 1])
Nb_x = 1000
cumul_signal = np.array([])#np.zeros(shape = (Nb_x,arr.shape[0]))
valid_x = [9999]

for x in range(1,Nb_x+1):

  running_sum = np.cumsum(np.array([-5, 4, -2, 3, 1])) + x
  if ~(np.any(running_sum < 0)):

    #cumul_signal[x-1,:] = running_sum
    print(running_sum)
    valid_x.append(x)
    cumul_signal= np.append(cumul_signal,running_sum)

cumul_signal = np.reshape(cumul_signal,(int(cumul_signal.shape[0]/arr.shape[0]),arr.shape[0]))